name: charcode
version: 1.2.0
description: >
  Constants for ASCII and common non-ASCII character codes.

  When working with characters in Dart, there is no simple way to
  represent the code point of a character.
  This library declares readable symbolic names for character codes.
homepage: http://www.dartlang.org
environment:
  sdk: '>=2.9.0-18.0 <2.9.0'

dependencies:
  pedantic: '>=1.9.0 <2.0.0'
