name: charcode
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: >
  Constants for ASCII and common non-ASCII character codes.

  When working with characters in Dart, there is no simple way to
  represent the code point of a character.
  This library declares readalbe symbolic names for character codes.
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
