name: charcode
version: 1.2.0-nullsafety.3
description: >
  Constants for ASCII and common non-ASCII character codes.

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.12.0'

dev_dependencies:
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
