name: charcode
version: 1.3.0
repository: https://github.com/lrhn/charcode
description: >-
  Constants for ASCII and common non-ASCII character codes.

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety
  lints: ^1.0.0
