name: charcode
version: 1.2.0-nullsafety
description: >-
  Constants for ASCII and common non-ASCII character codes represented by
  top-level constants.
homepage: https://github.com/dart-lang/charcode

environment:
  sdk: '>=2.9.0-18.0 <2.9.0'

dev_dependencies:
  pedantic: ^1.0.0
